name: flutter_blur
repository: https://github.com/shirvanie/flutter_blur/tree/master/
issue_tracker: https://github.com/shirvanie/flutter_blur/issues
homepage: https://github.com/shirvanie/flutter_blur
description: Flutter Blur
email: ihamedshirvani@gmail.com
version: 0.0.2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
